name: ASPIS main CI

env:
  LLVM_INSTALL_DIR: /opt/llvm-21

on:
  - push
  - workflow_dispatch

jobs:
  compile-ASPIS:
    runs-on: ubuntu-latest
    container:
      image: docker.io/ledmington/aspis-deps:llvm21

    steps:
      - name: Checking out ASPIS
        uses: actions/checkout@v4
        with:
          path: ASPIS
          submodules: recursive
          fetch-depth: 0

      - name: Compiling ASPIS
        shell: bash
        working-directory: ${{ github.workspace }}/ASPIS
        run: |
          cmake -B build -DLLVM_DIR=${{ env.LLVM_INSTALL_DIR }}/lib/cmake/llvm
          cmake --build build

      - name: Install Python requirements
        shell: bash
        working-directory: ${{ github.workspace }}/ASPIS/testing
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Testing ASPIS
        shell: bash
        working-directory: ${{ github.workspace }}/ASPIS/testing
        run: |
          source .venv/bin/activate
          pytest test.py --no-header -v

      - name: Upload comparison counter artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: comparison-counter
          path: ${{ github.workspace }}/ASPIS/testing/build/comparison_counter.csv
          if-no-files-found: warn

      - name: Upload failed test IR artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-out-ll
          path: |
            ASPIS/testing/failed-out-ll/**
          if-no-files-found: warn
